name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Validate schema fixtures
        run: python scripts/validate_schema.py

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
